spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  profiles:
    include: oauth
  session:
    store-type: jdbc
  h2:
    console:
      enabled: true
